const RESOURCE = 'REPORTS'

export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const CLEAR_REPORTS = `${RESOURCE}/CLEAR_REPORTS`

export const CREATE_REPORTS_GROUP = `${RESOURCE}/CREATE_REPORTS_GROUP`

export const READ_REPORT_GROUPS_BY_ADMIN = `${RESOURCE}/READ_REPORT_GROUPS_BY_ADMIN`
export const READ_REPORTS_BY_ADMIN = `${RESOURCE}/READ_REPORTS_BY_ADMIN`
export const READ_REPORTS_BY_USER = `${RESOURCE}/READ_REPORTS_BY_USER`
export const READ_ACCOUNT_REPORTS_BY_ADMIN = `${RESOURCE}/READ_ACCOUNT_REPORTS_BY_ADMIN`
export const READ_USERS_REPORTS_BY_ADMIN = `${RESOURCE}/READ_USERS_REPORTS_BY_ADMIN`

export const UPDATE_REPORT_ACTIVE_STATE_BY_ADMIN = `${RESOURCE}/UPDATE_REPORT_ACTIVE_STATE_BY_ADMIN`
export const UPDATE_REPORTS_GROUP = `${RESOURCE}/UPDATE_REPORTS_GROUP`
