const RESOURCE = `INSTANCES`;

export const ERROR = `${RESOURCE}/ERROR`;
export const LOADING = `${RESOURCE}/LOADING`;
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`;

export const GET_ALL_INSTANCES = `${RESOURCE}/GET_ALL_INSTANCES`;
export const GET_INSTANCE_BY_ID = `${RESOURCE}/GET_INSTANCE_BY_ID`;
export const CREATE_INSTANCE = `${RESOURCE}/CREATE_INSTANCE`;
export const UPDATE_INSTANCE = `${RESOURCE}/UPDATE_INSTANCE`;
export const DELETE_INSTANCE = `${RESOURCE}/DELETE_INSTANCE`;
export const ACTIVATE_INSTANCE = `${RESOURCE}/ACTIVATE_INSTANCE`;

export const GET_INSTANCES_BY_ACCOUNT = `${RESOURCE}/GET_INSTANCES_BY_ACCOUNT`;
export const ASSIGN_INSTANCE_TO_ACCOUNT = `${RESOURCE}/ASSIGN_INSTANCE_TO_ACCOUNT`;
export const REMOVE_INSTANCE_FROM_ACCOUNT = `${RESOURCE}/REMOVE_INSTANCE_FROM_ACCOUNT`;

export const SYNC_INSTANCE_WORKSPACES = `${RESOURCE}/SYNC_INSTANCE_WORKSPACES`;

export const GET_ACCOUNTS_LIST = `${RESOURCE}/GET_ACCOUNTS_LIST`;
