const RESOURCE = `ADMINS`;

export const ERROR = `${RESOURCE}/ERROR`;
export const LOADING = `${RESOURCE}/LOADING`;
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`;

export const READ_LOGO = `${RESOURCE}/READ_LOGO`;
export const READ_ADMINS_BY_SUPERUSER = `${RESOURCE}/READ_ADMINS_BY_SUPERUSER`;
export const READ_USERS_WORKSPACE = `${RESOURCE}/READ_USERS_WORKSPACE`;
export const UPDATE_LOGO = `${RESOURCE}/UPDATE_LOGO`;
export const ACCEPT_TERMS_AND_CONDITIONS = `${RESOURCE}/ACCEPT_TERMS_AND_CONDITIONS`;

export const CHANGE_USER_PASSWORD = `${RESOURCE}/CHANGE_USER_PASSWORD`;
