const RESOURCE = `ROLES`;

export const ERROR = `${RESOURCE}/ERROR`;
export const LOADING = `${RESOURCE}/LOADING`;
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`;

export const GET_ALL_ROLES = `${RESOURCE}/GET_ALL_ROLES`;
export const GET_ROLE_BY_ID = `${RESOURCE}/GET_ROLE_BY_ID`;

export const GET_USER_ROLES = `${RESOURCE}/GET_USER_ROLES`;
export const ASSIGN_ROLE_TO_USER = `${RESOURCE}/ASSIGN_ROLE_TO_USER`;
export const REMOVE_ROLE_FROM_USER = `${RESOURCE}/REMOVE_ROLE_FROM_USER`;
