const RESOURCE = `ACCOUNTS`;

export const ERROR = `${RESOURCE}/ERROR`;
export const LOADING = `${RESOURCE}/LOADING`;
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`;
export const READ_LOGO_BY_SUBDOMAIN = `${RESOURCE}/READ_LOGO_BY_SUBDOMAIN`;
export const GET_ALL_ACCOUNTS = `${RESOURCE}/GET_ALL_ACCOUNTS`;
export const CREATE_ACCOUNT = `${RESOURCE}/CREATE_ACCOUNT`;
export const UPDATE_ACCOUNT = `${RESOURCE}/UPDATE_ACCOUNT`;
export const GET_ACCOUNT_BY_ID = `${RESOURCE}/GET_ACCOUNT_BY_ID`;
