const RESOURCE = `DASHBOARDS`;

export const ERROR = `${RESOURCE}/ERROR`;
export const LOADING = `${RESOURCE}/LOADING`;
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`;

export const GET_ALL_DASHBOARDS = `${RESOURCE}/GET_ALL_DASHBOARDS`;
export const GET_DASHBOARD_BY_ID = `${RESOURCE}/GET_DASHBOARD_BY_ID`;
export const CREATE_DASHBOARD = `${RESOURCE}/CREATE_DASHBOARD`;
export const UPDATE_DASHBOARD = `${RESOURCE}/UPDATE_DASHBOARD`;
export const DELETE_DASHBOARD = `${RESOURCE}/DELETE_DASHBOARD`;
export const ACTIVATE_DASHBOARD = `${RESOURCE}/ACTIVATE_DASHBOARD`;

export const GET_DASHBOARDS_BY_USER = `${RESOURCE}/GET_DASHBOARDS_BY_USER`;
export const GET_DASHBOARD_EMBED_INFO = `${RESOURCE}/GET_DASHBOARD_EMBED_INFO`;
export const GET_DASHBOARD_USERS = `${RESOURCE}/GET_DASHBOARD_USERS`;

export const ASSIGN_DASHBOARD_TO_USER = `${RESOURCE}/ASSIGN_DASHBOARD_TO_USER`;
export const REMOVE_DASHBOARD_FROM_USER = `${RESOURCE}/REMOVE_DASHBOARD_FROM_USER`;

export const EXPORT_DASHBOARD_CSV = `${RESOURCE}/EXPORT_DASHBOARD_CSV`;
export const SEND_DASHBOARD_EMAIL = `${RESOURCE}/SEND_DASHBOARD_EMAIL`;
export const GET_DASHBOARD_EMBEDDED_CONFIG = `${RESOURCE}/GET_DASHBOARD_EMBEDDED_CONFIG`;
export const GET_REPORTS_LISTS = `${RESOURCE}/GET_REPORTS_LISTS`;
export const GET_DASHBOARDS_INSTANCES = `${RESOURCE}/GET_DASHBOARDS_INSTANCES`;
