const RESOURCE = `USERS_DASHBOARDS`;

export const ERROR = `${RESOURCE}/ERROR`;
export const LOADING = `${RESOURCE}/LOADING`;
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`;

export const GET_USER_DASHBOARDS = `${RESOURCE}/GET_USER_DASHBOARDS`;
export const GET_DASHBOARD_USERS = `${RESOURCE}/GET_DASHBOARD_USERS`;
export const ASSIGN_DASHBOARD_TO_USER = `${RESOURCE}/ASSIGN_DASHBOARD_TO_USER`;
export const REMOVE_DASHBOARD_FROM_USER = `${RESOURCE}/REMOVE_DASHBOARD_FROM_USER`;
export const BULK_ASSIGN_DASHBOARDS = `${RESOURCE}/BULK_ASSIGN_DASHBOARDS`;
