const RESOURCE = "WORKSPACES";

export const ERROR = `${RESOURCE}/ERROR`;
export const LOADING = `${RESOURCE}/LOADING`;
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`;
export const CLEAR_WORKSPACES = `${RESOURCE}/CLEAR_WORKSPACES`;

export const READ_WORKSPACES_BY_ADMIN = `${RESOURCE}/READ_WORKSPACES_BY_ADMIN`;
export const READ_WORKSPACES_BY_USER = `${RESOURCE}/READ_WORKSPACES_BY_USER`;

export const GET_ALL_WORKSPACES = `${RESOURCE}/GET_ALL_WORKSPACES`;
export const GET_WORKSPACE_BY_ID = `${RESOURCE}/GET_WORKSPACE_BY_ID`;
export const CREATE_WORKSPACE = `${RESOURCE}/CREATE_WORKSPACE`;
export const UPDATE_WORKSPACE = `${RESOURCE}/UPDATE_WORKSPACE`;
export const DELETE_WORKSPACE = `${RESOURCE}/DELETE_WORKSPACE`;
export const ACTIVATE_WORKSPACE = `${RESOURCE}/ACTIVATE_WORKSPACE`;
export const GET_INSTANCES_LIST = `${RESOURCE}/GET_INSTANCES_LIST`;
export const GET_ACCOUNTS_LIST = `${RESOURCE}/GET_ACCOUNTS_LIST`;
