const RESOURCE = 'WORKSPACES'

export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const CLEAR_WORKSPACES = `${RESOURCE}/CLEAR_WORKSPACES`

export const READ_WORKSPACES_BY_ADMIN = `${RESOURCE}/READ_WORKSPACES_BY_ADMIN`
export const READ_WORKSPACES_BY_USER = `${RESOURCE}/READ_WORKSPACES_BY_USER`
