const RESOURCE = 'SECTIONS'

export const ERROR = `${RESOURCE}/ERROR`
export const LOADING = `${RESOURCE}/LOADING`
export const CLEAR_MESSAGE = `${RESOURCE}/CLEAR_MESSAGE`
export const CLEAR_SECTIONS = `${RESOURCE}/CLEAR_SECTIONS`

export const CREATE = `${RESOURCE}/CREATE`

export const READ_SECTIONS_BY_ADMIN = `${RESOURCE}/READ_SECTIONS_BY_ADMIN`
export const READ_SECTIONS_BY_USER = `${RESOURCE}/READ_SECTIONS_BY_USER`
export const READ = `${RESOURCE}/READ`

export const UPDATE = `${RESOURCE}/UPDATE`

export const DELETE = `${RESOURCE}/DELETE`
